import type { ExperienceItem } from './types';

export const experience: ExperienceItem[] = [
  {
    company: { en: 'Gazprom Inform LLC', ru: 'ООО «Газпром информ»' },
    role: { en: 'Full-Stack Web Developer', ru: 'Full-Stack веб-разработчик' },
    period: { en: 'Aug 2023 — Present', ru: 'Авг 2023 — настоящее время' },
    context: {
      en: 'Develop and support internal enterprise services from requirement clarification and estimation to implementation, integrations, releases and production support.',
      ru: 'Разрабатываю и поддерживаю внутренние корпоративные сервисы: от уточнения требований и оценки до реализации, интеграций, выпуска и сопровождения в эксплуатации.',
    },
    points: {
      en: [
        'Built a meeting-room booking service used across an organisation of 3,000+ employees, replacing manual approval workflows and saving an estimated 17.5 employee-hours per week.',
        'Developed an internal AI/RAG assistant for regulatory knowledge search and drafting internal documents, reducing typical processing time from 2–5 hours to 15–20 minutes per request across a workflow handling roughly 10–40 requests per day.',
        'Developed additional internal services for bookings, access requests and cross-system applications, reducing repetitive manual work and the risk of human error.',
        'Built workflows that generate commercial proposals and submit requests through a corporate SOAP integration bus, automating processes that span multiple enterprise systems.',
        'Integrated applications with REST and SOAP services: validated and transformed large flat datasets into structured hierarchical domain models.',
        'Work directly with stakeholders on requirements, effort estimation, task decomposition, solution design, prototyping and production releases; use Python with Pandas and NumPy for operational analysis and incident investigation.',
      ],
      ru: [
        'С нуля разработал сервис бронирования переговорных для организации с 3000+ сотрудниками: заменил ручную цепочку согласований и сократил трудозатраты примерно на 17,5 человеко-часа в неделю.',
        'Разработал внутренний AI/RAG-ассистент для поиска по регламентам и подготовки внутренних документов: типичное время обработки запроса сократилось с 2–5 часов до 15–20 минут при потоке примерно 10–40 запросов в день.',
        'Разрабатывал другие внутренние сервисы для бронирований, заявок на доступ и передачи заявок между системами, сокращая ручную работу и влияние человеческого фактора.',
        'Автоматизировал процессы формирования коммерческих предложений и отправки заявок через корпоративную SOAP-шину в цепочках, охватывающих несколько корпоративных систем.',
        'Интегрировал приложения с REST- и SOAP-сервисами: валидировал и преобразовывал большие плоские наборы данных в структурированные иерархические модели.',
        'Работаю напрямую с заказчиками: уточняю требования, оцениваю и декомпозирую задачи, проектирую решения, создаю прототипы и выпускаю их в production; использую Python, Pandas и NumPy для анализа эксплуатационных данных и разбора инцидентов.',
      ],
    },
    tech: [
      'PHP',
      '1C-Bitrix',
      'JavaScript',
      'jQuery',
      'Vue',
      'MySQL',
      'SQL',
      'REST',
      'SOAP',
      'Python',
      'RAG',
      'GitLab CI/CD',
      'Linux',
    ],
  },
  {
    company: { en: 'Onpeak Digital', ru: 'Onpeak Digital' },
    role: { en: 'Full-Stack Web Developer', ru: 'Full-Stack веб-разработчик' },
    period: { en: 'Mar 2021 — Sep 2022', ru: 'Мар 2021 — сен 2022' },
    context: {
      en: 'Delivered and supported e-commerce and corporate web projects across the full development cycle.',
      ru: 'Разрабатывал и поддерживал e-commerce и корпоративные веб-проекты на всём цикле разработки.',
    },
    points: {
      en: [
        'Worked across 10+ client web projects, including large e-commerce platforms and corporate websites.',
        'Improved slow legacy sites using Chrome DevTools, Lighthouse and PageSpeed Insights; implemented lazy loading, image optimisation, Bitrix Composite Site, caching, JavaScript/API optimisation and database-query improvements.',
        'Introduced Docker and Docker Compose to make development environments and deployments more reproducible.',
        'Mentored two junior developers, reviewed code, decomposed requirements and distributed tasks within Scrum and Kanban workflows.',
        'Investigated production bottlenecks and defects across PHP backend, JavaScript frontend and MySQL/database layers.',
      ],
      ru: [
        'Работал более чем с 10 клиентскими веб-проектами, включая крупные интернет-магазины и корпоративные сайты.',
        'Оптимизировал медленные legacy-сайты с помощью Chrome DevTools, Lighthouse и PageSpeed Insights: внедрял lazy loading, оптимизацию изображений, «Композитный сайт» Битрикс, кеширование, оптимизацию JavaScript/API и запросов к базе данных.',
        'Внедрил Docker и Docker Compose, чтобы окружения разработки и развёртывание были более воспроизводимыми.',
        'Был наставником двух начинающих разработчиков: проводил ревью кода, декомпозировал требования и распределял задачи в Scrum/Kanban.',
        'Разбирал production-проблемы и узкие места на уровне PHP backend, JavaScript frontend и MySQL.',
      ],
    },
    tech: [
      '1C-Bitrix',
      'PHP',
      'JavaScript',
      'jQuery',
      'MySQL',
      'Docker',
      'Docker Compose',
      'HTML',
      'CSS',
    ],
  },
  {
    company: { en: 'ITooLabs', ru: 'ITooLabs' },
    role: {
      en: 'QA & Web Developer',
      ru: 'QA и веб-разработчик',
    },
    period: { en: 'Sep 2018 — Mar 2020', ru: 'Сен 2018 — мар 2020' },
    context: {
      en: 'Combined QA and web development in IP telephony and cloud communications, working part-time on backend functionality, integrations and service monitoring.',
      ru: 'Совмещал тестирование и веб-разработку в IP-телефонии и облачных коммуникациях, на частичной занятости работая с backend-функциональностью, интеграциями и мониторингом сервисов.',
    },
    points: {
      en: [
        'Developed backend and frontend functionality using PHP, JavaScript, SQL, HTML and CSS, including a customer feedback widget subsystem with its own data storage.',
        'Integrated amoCRM, Bitrix24, RetailCRM and custom CRM systems with telephony services using REST APIs and webhooks.',
        'Worked with SIP/IP-telephony workflows and external telecom integrations; configured Zabbix monitoring and investigated service incidents.',
        'Worked with Go-based APIs and legacy frontend migration tasks alongside manual QA, debugging and defect reporting.',
      ],
      ru: [
        'Разрабатывал backend- и frontend-функциональность на PHP, JavaScript, SQL, HTML и CSS, включая подсистему виджета обратной связи с собственным хранением данных.',
        'Интегрировал amoCRM, Bitrix24, RetailCRM и кастомные CRM с телефонией через REST API и webhooks.',
        'Работал с SIP/IP-телефонией и внешними телеком-интеграциями; настраивал мониторинг Zabbix и разбирал инциденты.',
        'Работал с Go-based API и задачами переноса legacy frontend-кода, совмещая разработку с ручным тестированием, отладкой и описанием дефектов.',
      ],
    },
    tech: [
      'PHP',
      'JavaScript',
      'SQL',
      'REST APIs',
      'Webhooks',
      'SIP / IP telephony',
      'CRM integrations',
      'Go',
      'Zabbix',
      'Manual QA',
    ],
  },
];
