import type { ProjectItem } from './types';

export const projects: ProjectItem[] = [
  {
    id: 'demiurge',
    name: 'Demiurge Assistant',
    featured: true,
    category: 'ai',
    status: 'active-development',
    image: './images/articles/demiurge-ai-chat/entity-a17.png',
    imageWidth: 1470,
    imageHeight: 739,
    imagePosition: 'center top',
    imageAlt: {
      en: 'Demiurge Assistant structured A-17 character page',
      ru: 'Структурированная карточка персонажа A-17 в Demiurge Assistant',
    },
    gallery: [
      {
        src: './images/articles/demiurge-ai-chat/encyclopedia.png',
        width: 1460,
        height: 775,
        alt: {
          en: 'The current Demiurge Assistant world encyclopedia with typed entity cards',
          ru: 'Актуальная энциклопедия мира Demiurge Assistant с типизированными карточками сущностей',
        },
        caption: {
          en: 'World encyclopedia and entity filters',
          ru: 'Энциклопедия мира и фильтры сущностей',
        },
      },
      {
        src: './images/articles/demiurge-ai-chat/entity-a17.png',
        width: 1470,
        height: 739,
        alt: {
          en: 'The current structured A-17 character page in Demiurge Assistant',
          ru: 'Актуальная структурированная карточка персонажа A-17 в Demiurge Assistant',
        },
        caption: {
          en: 'Structured character knowledge',
          ru: 'Структурированные знания о персонаже',
        },
      },
      {
        src: './images/articles/demiurge-ai-chat/relationship-graph.png',
        width: 642,
        height: 723,
        alt: {
          en: 'The current relationship graph connecting entities in the world of Eon',
          ru: 'Актуальный граф связей между сущностями мира Эон',
        },
        caption: {
          en: 'Directed relationships between world entities',
          ru: 'Направленные связи между сущностями мира',
        },
      },
      {
        src: './images/articles/demiurge-ai-chat/knowledge-sources.png',
        width: 2180,
        height: 725,
        alt: {
          en: 'Knowledge sources and a completed semantic index in Demiurge Assistant',
          ru: 'Источники знаний и готовый семантический индекс в Demiurge Assistant',
        },
        caption: {
          en: 'Source ingestion and semantic indexing',
          ru: 'Загрузка источников и семантическая индексация',
        },
      },
      {
        src: './images/articles/demiurge-ai-chat/world-review.png',
        width: 2181,
        height: 735,
        alt: {
          en: 'A detailed world consistency review generated by Demiurge Assistant',
          ru: 'Подробная проверка целостности мира, созданная Demiurge Assistant',
        },
        caption: {
          en: 'World review before applying changes',
          ru: 'Проверка мира перед применением изменений',
        },
      },
    ],
    accent: 'green',
    github: 'https://github.com/theDAREK497/demiurge-assistant',
    role: {
      en: 'Product Designer · Software Architect · Full-Stack Engineer',
      ru: 'Продуктовый дизайнер · Архитектор ПО · Full-Stack инженер',
    },
    summary: {
      en: 'A knowledge workspace for fictional worlds. AI suggests characters, facts and relationships; the author reviews what becomes part of the world.',
      ru: 'База знаний для вымышленных миров. ИИ предлагает персонажей, факты и связи, а автор решает, что станет частью мира.',
    },
    capabilities: {
      en: [
        'A shared knowledge base',
        'Human approval workflows',
        'Local and external LLM support',
        'Entity relationships',
      ],
      ru: [
        'Единая база знаний',
        'Подтверждение изменений человеком',
        'Локальные и внешние LLM',
        'Связи сущностей',
      ],
    },
    details: [
      {
        label: { en: 'Problem', ru: 'Проблема' },
        value: {
          en: 'Long-running AI chats mix facts and assumptions, lose context and make generated changes hard to review.',
          ru: 'В долгих диалогах с ИИ смешиваются факты и предположения, теряется контекст, а предложенные изменения сложно проверять.',
        },
      },
      {
        label: { en: 'Knowledge model', ru: 'Модель знаний' },
        value: {
          en: 'Persistent entities and relationships keep confirmed information separate from AI suggestions.',
          ru: 'Факты хранятся в карточках сущностей и связях между ними — отдельно от предложений ИИ.',
        },
      },
      {
        label: { en: 'Human approval', ru: 'Подтверждение человеком' },
        value: {
          en: 'AI actions remain reviewable before they become part of the durable knowledge base.',
          ru: 'Пользователь проверяет предложения ИИ и решает, какие изменения сохранить в базе знаний.',
        },
      },
      {
        label: { en: 'Local-first approach', ru: 'Локальный подход' },
        value: {
          en: 'Provider abstraction supports local and external LLMs while keeping the user in control of persistent data.',
          ru: 'Можно подключать локальные и внешние языковые модели через общий интерфейс. База знаний остаётся под контролем пользователя.',
        },
      },
      {
        label: { en: 'Trade-offs', ru: 'Компромиссы' },
        value: {
          en: 'Changes require the author’s attention. This is slower than full automation, but the model cannot quietly rewrite the world.',
          ru: 'Изменения требуют внимания автора. Это медленнее полной автоматизации, зато модель не может незаметно переписать мир.',
        },
      },
    ],
    results: {
      en: [
        'Built draft generation, entity editing and relationship creation with human review before changes are applied.',
        'An ongoing personal experiment, tested by me and one other person — not yet validated for a wider audience.',
      ],
      ru: [
        'Реализованы генерация черновиков, заполнение сущностей и создание связей с проверкой перед применением изменений.',
        'Личный эксперимент в разработке. Кроме меня, им пользовался один человек; для широкой аудитории продукт пока не проверен.',
      ],
    },
    tech: [
      'React',
      'FastAPI',
      'SQLite',
      'Local LLM',
      'RAG',
      'Human-in-the-loop',
    ],
  },
  {
    id: 'astrocode',
    name: 'AstroCode',
    featured: true,
    category: 'product',
    status: 'live',
    image: './images/projects/astrocode-dashboard.png',
    imageWidth: 1500,
    imageHeight: 1206,
    imagePosition: 'center top',
    imageAlt: {
      en: 'AstroCode dashboard with personalized calculation modules',
      ru: 'Главный экран AstroCode с модулями персональных расчётов',
    },
    gallery: [
      {
        src: './images/projects/astrocode-dashboard.png',
        width: 1500,
        height: 1206,
        alt: {
          en: 'AstroCode dashboard with personalized calculation modules',
          ru: 'Главный экран AstroCode с модулями персональных расчётов',
        },
        caption: {
          en: 'Cross-platform product dashboard',
          ru: 'Главный экран кроссплатформенного продукта',
        },
      },
      {
        src: './images/projects/astrocode-natal-chart.png',
        width: 1501,
        height: 1180,
        alt: {
          en: 'AstroCode natal chart report with aura color and essential dignities',
          ru: 'Натальная карта AstroCode с цветом ауры и эссенциальными достоинствами',
        },
        caption: {
          en: 'Natal chart and personalized report',
          ru: 'Натальная карта и персональный отчёт',
        },
      },
      {
        src: './images/projects/astrocode-insights.png',
        width: 1500,
        height: 1200,
        alt: {
          en: 'AstroCode psychological portrait and elemental balance visualizations',
          ru: 'Психологический портрет и баланс стихий в AstroCode',
        },
        caption: {
          en: 'Visualized personal insights',
          ru: 'Визуализация персональных характеристик',
        },
      },
    ],
    accent: 'violet',
    link: 'https://astrocode-app.ru/',
    role: {
      en: 'Independent Product Engineer',
      ru: 'Независимый продуктовый инженер',
    },
    summary: {
      en: 'A subscription app launched on web, Telegram and Android. I built the product, connected payments and account access, and received the first paid subscription.',
      ru: 'Приложение с подпиской для веба, Telegram и Android. Самостоятельно собрал продукт, подключил платежи и доступ к аккаунту, получил первую платную подписку.',
    },
    capabilities: {
      en: [
        'Web, Telegram and Android delivery',
        'Payments and subscriptions',
        'Account and access flows',
        'Store publishing',
      ],
      ru: [
        'Веб, Telegram и Android',
        'Платежи и подписки',
        'Аккаунты и управление доступом',
        'Публикация в магазинах',
      ],
    },
    details: [
      {
        label: { en: 'My role', ru: 'Моя роль' },
        value: {
          en: 'Owned product concept, requirements, frontend, backend, authentication, subscriptions, publishing and iteration.',
          ru: 'Отвечал за концепцию, требования, frontend, backend, авторизацию, подписки, публикацию и развитие продукта.',
        },
      },
      {
        label: { en: 'Platforms', ru: 'Платформы' },
        value: {
          en: 'Web application, Telegram Mini App, Android, RuStore and Huawei AppGallery.',
          ru: 'Веб-приложение, Telegram Mini App, Android, RuStore и Huawei AppGallery.',
        },
      },
      {
        label: { en: 'Payment flow', ru: 'Платёжный поток' },
        value: {
          en: 'Connected YooKassa payments, webhooks and subscription access across product surfaces.',
          ru: 'Подключил оплату через ЮKassa, обработку вебхуков и доступ по подписке на разных платформах.',
        },
      },
      {
        label: {
          en: 'Cross-platform challenge',
          ru: 'Кроссплатформенная задача',
        },
        value: {
          en: 'Aligned account, access and subscription state between web, Telegram and Android releases.',
          ru: 'Согласовал состояние аккаунта, доступа и подписки между вебом, Telegram и Android-релизами.',
        },
      },
    ],
    results: {
      en: [
        'Publicly launched across web, Telegram and Android.',
        '804 store page views, 11 installs and 1 paid monthly subscription from 01 June 2026 to 13 July 2026.',
        'These early results were recorded without an active advertising campaign.',
      ],
      ru: [
        'Публично запущен в вебе, Telegram и Android.',
        '804 просмотра страницы магазина, 11 установок и 1 платная месячная подписка за период с 1 июня по 13 июля 2026 года.',
        'Эти первые результаты получены без активной рекламной кампании.',
      ],
    },
    tech: ['React', 'TypeScript', 'Node.js', 'YooKassa', 'Telegram', 'Android'],
  },
  {
    id: 'archive-assistant',
    name: 'Archive Assistant Bot',
    featured: false,
    category: 'ai',
    status: 'prototype',
    image: './images/projects/archive-assistant-intro.jpg',
    imageWidth: 1152,
    imageHeight: 2286,
    imagePosition: 'center top',
    imageAlt: {
      en: 'Telegram conversation with Archive Assistant and source references',
      ru: 'Диалог с Archive Assistant в Telegram со ссылками на источники',
    },
    gallery: [
      {
        src: './images/projects/archive-assistant-intro.jpg',
        width: 1152,
        height: 2286,
        alt: {
          en: 'Archive Assistant Telegram bot introduction and example questions',
          ru: 'Приветствие Archive Assistant в Telegram и примеры вопросов',
        },
        caption: {
          en: 'Telegram onboarding and suggested questions',
          ru: 'Знакомство с ботом и примеры запросов',
        },
      },
      {
        src: './images/projects/archive-assistant-answer.jpg',
        width: 1152,
        height: 785,
        alt: {
          en: 'Archive Assistant answer with numbered source references',
          ru: 'Ответ Archive Assistant с пронумерованными ссылками на источники',
        },
        caption: {
          en: 'Source-linked answer from the private archive',
          ru: 'Ответ по частному архиву со ссылками на источники',
        },
      },
    ],
    accent: 'coral',
    github: 'https://github.com/theDAREK497/archive-assistant-bot',
    role: {
      en: 'RAG Prototype · Telegram Interface',
      ru: 'RAG-прототип · Telegram-интерфейс',
    },
    summary: {
      en: 'A Telegram bot that answers questions about a private document archive. It searches locally, generates an answer and links back to the source material.',
      ru: 'Telegram-бот, который отвечает на вопросы по частному архиву документов: ищет информацию локально, формирует ответ и даёт ссылки на источники.',
    },
    capabilities: {
      en: [
        'Document parsing',
        'Semantic retrieval',
        'Local generation',
        'Source-linked answers',
      ],
      ru: [
        'Разбор документов',
        'Семантический поиск',
        'Локальная генерация',
        'Ссылки на источники',
      ],
    },
    details: [
      {
        label: { en: 'Pipeline', ru: 'Пайплайн' },
        value: {
          en: 'Document collection, parsing, semantic chunking, embeddings, FAISS retrieval and local generation.',
          ru: 'Сбор и разбор документов, семантический чанкинг, эмбеддинги, поиск FAISS и локальная генерация.',
        },
      },
      {
        label: { en: 'Privacy', ru: 'Приватность' },
        value: {
          en: 'Private documentation can be processed locally with a Qwen model through LM Studio.',
          ru: 'Частная документация может обрабатываться локально моделью Qwen через LM Studio.',
        },
      },
      {
        label: { en: 'Answer design', ru: 'Формат ответа' },
        value: {
          en: 'Responses include references back to the retrieved source material.',
          ru: 'Ответы содержат ссылки на найденные исходные материалы.',
        },
      },
    ],
    results: {
      en: [
        'Built and tested the complete local RAG workflow for Russian-language documentation.',
      ],
      ru: [
        'Собран и протестирован полный локальный RAG-процесс для русскоязычной документации.',
      ],
    },
    tech: ['Python', 'FAISS', 'Qwen', 'LM Studio', 'Telegram', 'RAG'],
  },
];
